break test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,16 +1,48 @@
 version: 2.1
-orbs:
-  compass: atlassian-labs/compass@0.1.2
-  maven: circleci/maven@1.3.0
-  cypress: cypress-io/cypress@2.2.0
-          
+      
+workflows:
+  main:
+    jobs:
+      - java-checkstyle
+      - java-test-and-code-cov:
+          requires: [ java-checkstyle, python-checkstyle ]
+      - python-checkstyle
+      - python-test:
+          requires: [ java-checkstyle, python-checkstyle ]
+      - skaffold-build-push:
+          context: cera-vault-oidc
+          requires: [ java-test-and-code-cov, python-test ]
+      - deploy:
+          name: Deploy Dev
+          requires: [ skaffold-build-push ]
+          context: [ compass-integration-bank-of-aion, cera-vault-oidc ]
+          post-steps:
+            - compass/notify_deployment:
+                token_name: COMPASS_CCI_TOKEN
+                environment_type: development
+      - e2e:
+          requires: [ Deploy Dev ]
+      - deploy:
+          name: Deploy Production
+          requires: [ e2e ]
+          boa-environment: prod
+          context: [ compass-integration-bank-of-aion, cera-vault-oidc-prod ]
+          filters:
+            branches:
+              only: [ main ]
+          post-steps:
+            - compass/notify_deployment:
+                token_name: COMPASS_CCI_TOKEN
+                environment_type: production
+                environment: CERA-Cluster-Namer-Prod
+
 executors:
   with-chrome:
     docker:
       - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
   base:
     docker:
-      - image: cimg/deploy:2022.07
+      - image: cimg/deploy:2022.08
   jdk17:
     docker:
       - image: cimg/openjdk:17.0.3
@@ -19,7 +51,6 @@ executors:
   python38:
     docker:
       - image: cimg/python:3.8
-
 
 jobs:
   python-checkstyle:
@@ -72,14 +103,13 @@ jobs:
     steps:
       - checkout
       - run: mkdir test-reports
-      - run: mvn help:effective-pom > /tmp/zpom.xml
       - restore_cache:
           keys:
-            - v1-mvn-full-{{ checksum "/tmp/zpom.xml" }}
-            - v1-mvn-full-
+            - v2-mvn-full-{{ .Branch }}
+            - v2-mvn-full-
       - run: mvn dependency:go-offline
       - save_cache:
-          key: v1-mvn-full-{{ checksum "/tmp/zpom.xml" }}
+          key: v2-mvn-full-{{ .Branch }}
           paths:
             - ~/.m2
       - run: |
@@ -109,27 +139,31 @@ jobs:
       steps:
         - checkout
         - run: |
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
             curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
             sudo install skaffold /usr/local/bin/
-        - enable-oidc
+        - load-credentials    
         - setup_remote_docker:
             docker_layer_caching: true
-        - run: mvn help:effective-pom > /tmp/zpom.xml
         - restore_cache:
             keys:
-              - v1-mvn-full-{{ checksum "/tmp/zpom.xml" }}
-              - v1-mvn-full-
+              - v2-mvn-full-{{ .Branch }}
+              - v2-mvn-full-
+        - restore_cache:
+            keys:
+              - v1-skaffold-{{ .Branch }}
+              - v1-skaffold-
         - run: |
-            #this is temp use of admin rights while we bukld out nexus
-            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 483285841698.dkr.ecr.us-west-2.amazonaws.com
+            export DOCKER_TAG=build$(git rev-parse HEAD:src)
+            echo "${DOCKER_PWD}" | docker login --username ${DOCKER_LOGIN} --password-stdin docker.nexus.cera.circleci-labs.com
             # seems like skaffold jib needs a eird kick, hit me locally, passes on second run
             ./mvnw jib:_skaffold-fail-if-jib-out-of-date -Djib.requiredVersion=1.4.0 --projects src/ledgerwriter --also-make jib:_skaffold-files-v2 --quiet --batch-mode
             mkdir output
-            skaffold build --build-concurrency=4 --tag=build<<pipeline.number>> --default-repo=483285841698.dkr.ecr.us-west-2.amazonaws.com --file-output=output/tags.json
+            skaffold build --build-concurrency=4 --default-repo=docker.nexus.cera.circleci-labs.com --file-output=output/tags.json
             ls /tmp/
+        - save_cache:
+            key: v1-skaffold-{{ .Branch }}
+            paths:
+              - ~/.skaffold/cache
         - persist_to_workspace:
             root: output
             paths: [ 'tags.json' ]
@@ -138,28 +172,25 @@ jobs:
   deploy:
     executor: base
     parameters:
-      environment:
+      boa-environment:
         type: string
         default: dev
         description: Environment suffix used by namesapce and SA account name.
     environment:
-      K8_USER: boa-pipeline-<<parameters.environment>>
-      K8_URL: "https://82BD0213010A79DBD7EAF886E3E553E0.gr7.us-west-2.eks.amazonaws.com"
-      K8_CLUSTER: cera-solutions-eng
+      BOA_ENV: <<parameters.boa-environment>>
     steps:
       - checkout
-      - run: echo "Now using namespace ${K8_NAMESPACE}"
-      - use_service_account
+      - load-credentials
+      - run: echo "Now using ${K8S_USER}@${K8S_NAMESPACE}"
       - run: |
           sudo apt update && sudo apt install kubectl -y
-          kubectl config view
-          kubectl get serviceaccounts -n ${K8_NAMESPACE}
-      # temp whike using ecr
-      - run: | 
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install
-      - enable-oidc
+          echo ${K8S_CERT} | base64 -d > ca.crt
+          kubectl config set-cluster ${K8S_CLUSTER} --server=${K8S_URL} --certificate-authority=ca.crt
+          export DECODED_TOKEN=$(echo ${K8S_TOKEN} | base64 -d) #kubectl prints an encoded value, MUST decode it to work.
+          kubectl config set-credentials ${K8S_USER} --token=${DECODED_TOKEN}
+          kubectl config set-context default --user=${K8S_USER}  --cluster=${K8S_CLUSTER} --namespace ${K8S_NAMESPACE}
+          kubectl config use-context default
+          kubectl get serviceaccounts -n ${K8S_NAMESPACE}
       - attach_workspace:
           at: output
       - run: 
@@ -167,14 +198,14 @@ jobs:
           command: |
             curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
             sudo install skaffold /usr/local/bin/
-            skaffold deploy --default-repo=483285841698.dkr.ecr.us-west-2.amazonaws.com --namespace=${K8_NAMESPACE} --build-artifacts=output/tags.json
+            skaffold deploy --default-repo=docker.nexus.cera.circleci-labs.com --namespace=${K8S_NAMESPACE} --build-artifacts=output/tags.json
       - run:
           name: Wait for deployment
           command: |
-            kubectl wait deployment -n ${K8_NAMESPACE} frontend --for condition=Available=True --timeout=90s
+            kubectl wait deployment -n ${K8S_NAMESPACE} frontend --for condition=Available=True --timeout=90s
       - run: 
           name: Print Frontend URL
-          command: kubectl get service frontend -n ${K8_NAMESPACE} | awk '{print $4}'
+          command: kubectl get service frontend -n ${K8S_NAMESPACE} | awk '{print $4}'
   e2e:
     executor: with-chrome
     steps:
@@ -194,80 +225,33 @@ jobs:
           path: ui-tests/cypress/videos
       - store_artifacts:
           path: ui-tests/cypress/screenshots    
-   
-workflows:
-  main:
-    jobs:
-      - java-checkstyle
-      - java-test-and-code-cov
-      - python-checkstyle
-      - python-test
-      - skaffold-build-push:
-          requires: [ python-test, java-test-and-code-cov ]
-          context: reference-arch-aws-oidc
-      - deploy:
-          name: Deploy Dev
-          requires: [ skaffold-build-push ]
-          context: [ reference-arch-aws-oidc, cera-boa-dev, compass-integration-bank-of-aion ]
-          post-steps:
-            - compass/notify_deployment:
-                token_name: COMPASS_CCI_TOKEN
-                environment_type: development
-      - e2e:
-          requires: [ Deploy Dev ]
-      - deploy:
-          name: Deploy Production
-          requires: [ e2e ]
-          context: [ reference-arch-aws-oidc, cera-boa-prod, compass-integration-bank-of-aion ]
-          filters:
-            branches:
-              only: [ main ]
-          post-steps:
-            - compass/notify_deployment:
-                token_name: COMPASS_CCI_TOKEN
-                environment_type: production
-                environment: CERA-Cluster-Namer-Prod
-
 
 commands:
-  use_service_account:
-  # This command uses the assigned context to hydrate a kubeconfig from the given service account.
-  # These values are automatically injected into the 2 app contexts by the `reference-architecture` project
+  load-credentials:
     steps:
       - run:
+          name: install vault agent (if not present)
           command: |
-            echo ${K8_CERT} | base64 -d > ca.crt
-            kubectl config set-cluster ${K8_CLUSTER} --server=${K8_URL} --certificate-authority=ca.crt
-            export DECODED_TOKEN=$(echo ${K8_TOKEN} | base64 -d) #kubectl prints an encoded value, MUST decode it to work.
-            kubectl config set-credentials ${K8_USER} --token=${DECODED_TOKEN}
-            kubectl config set-context default --user=${K8_USER}  --cluster=${K8_CLUSTER} --namespace ${K8_NAMESPACE}
-            kubectl config use-context default
-          name: Use K8s token & cert to create kubeconfig.
-
-  enable-oidc:
-    steps:
+            vault -h && exit 0 || echo "Installing vault"
+            #only runs if vault command avbove failed
+            cd /tmp
+            wget https://releases.hashicorp.com/vault/1.12.2/vault_1.12.2_linux_amd64.zip
+            unzip vault_1.12.2_linux_amd64.zip
+            sudo mv vault /usr/local/bin        
+            vault -h    
       - run:
-          name: authenticate-and-interact
+          name: Activate Vault Agent
           command: |
-            # use the OpenID Connect token to obtain AWS credentials
-            read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \<<< \
-              $(aws sts assume-role-with-web-identity \
-              --role-arn ${AWS_ROLE_ARN} \
-              --role-session-name "CircleCI-Pipeline-BoA" \
-              --web-identity-token $CIRCLE_OIDC_TOKEN \
-              --duration-seconds 3600 \
-              --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
-              --output text)
-            export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
-            # interact with AWS
-            aws sts get-caller-identity
-            echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $BASH_ENV
-            echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $BASH_ENV
-            echo "export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $BASH_ENV
-            source $BASH_ENV
+            echo $BOA_ENV
+            echo $CIRCLE_OIDC_TOKEN > .circleci/vault/token.json
+            vault agent -config=.circleci/vault/agent.hcl
+      - run:
+          command: |
+            source .circleci/vault/setenv
+            #export for other steps
+          name: Set Environment Variables from Vault
 
-# VS Code Extension Version: 1.0.0
-
-# VS Code Extension Version: 1.0.0
-
-# VS Code Extension Version: 1.1.1
+orbs:
+  compass: atlassian-labs/compass@0.1.2
+  maven: circleci/maven@1.3.0
+    
