SE-105: add CLI to python tests
SE-105: pyhon imports not wolkrkign through CLI..

SE-105: added CLI to java
there is a fun caveat with java that needs quite a hack to be
selective of which tests run.  I wrote this for maven orb
(which should be updated and made a command)

SE-105: fix nested path to tests"

SE-105: remove wildcard from sed

SE-105: replaced regex for java splitting

SE-105: remove failsafe

SE-105: remove failsafe

SE-105: remove failsafe

SE-105 the delta of the delta is my friend..

SE-105: should not pass empty file

SE-105: echo from tests run with tr

SE-105: echo from tests run with tr

SE-105: echo from tests run with tr

SE-105:remove .java from class names

SE-105: ignore failure of missing timings

SE-105: ignore failure of missing timings

cli not non-zero, more debug output

cli not non-zero, more debug output

cli not non-zero, more debug output

SE-105: use -Dtest=

SE-105: use -Dtest= (was missing -I, try witout

SE-105: add tr back for commas

SE-105: fail

dont skip after first fialure

always store test results

always store test results

grab filtered list from run

SE-105: tweak xargs

SE-105: tweak xargs

SE-105: get results always

xarg comand

tweak command again

SE-105: debug

SE-105: debug

SE-105: debug

SE-105: debug:

SE-105: maven skip fail if no tests on submodules

SE-105: demo test fails first run always

SE-105: demo test fails first run always

SE-105: demo test fails first run always

SE-105: demo test fails first run always

add job-only workspace for reruns

SE-105: pass jacoco in workspace

SE-105: pass jacoco in workspace

SE-105: pass jacoco in workspace

SE-105: pass jacoco in workspace

SE-105: pass jacoco in workspace

SE-105: pass jacoco in workspace

drop jacoco summary

SE-105: add test logic to demo

remove deplot filter [skip ci]

SE-105: test path typo [skip ci]

SE-105: revert demo script to use main

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,7 @@
 version: 2.1
 orbs:
   compass: atlassian-labs/compass@0.1.2
-  maven: circleci/maven@1.3.0
+  maven: circleci/maven@1.4
           
 executors:
   with-chrome:
@@ -46,7 +46,9 @@ jobs:
                 source $HOME/venv-$SERVICE/bin/activate
                 pip install --upgrade pip
                 pip install -r requirements.txt
-                python -m pytest --junit-xml=../../test-reports/report-${SERVICE}.xml -v -p no:warnings
+                #CLI wraps test runner to allow "rerun failed tests only"
+                TEST_FILES=$(circleci tests glob "tests/test_*.py")
+                echo $TEST_FILES | circleci tests run --command="xargs python -m pytest --junit-xml=../../test-reports/report-${SERVICE}.xml -v -p no:warnings" --verbose --split-by=timings
                 deactivate
               # return to previously saved path
               popd
@@ -80,28 +82,44 @@ jobs:
           key: v2-mvn-full-{{ .Branch }}
           paths:
             - ~/.m2
-      - run: |
-          ./mvnw test
-          for SERVICE in "balancereader" "ledgerwriter" "transactionhistory"; do
-          echo "checking $SERVICE..."
-          # save current working dir to memory and cd to src/$SERVICE
-          pushd src/$SERVICE
-          ../../mvnw jacoco:report
-          echo "Coverage for $SERVICE:"
-          awk -F, \
-          '{ instructions += $4 + $5; covered += $5 } END \
-          { print covered, "/", instructions, " instructions covered"; \
-          print int(100*covered/instructions), "% covered" }' \
-          target/site/jacoco/jacoco.csv
-          cp target/surefire-reports/*.xml ../../test-reports
-          # return to previously saved path
-          popd
-          done
+      - run:
+          environment:
+            PARAM_IT_PATTERN: '**/*IT*.java'
+            PARAM_TEST_DIR: 'src/**/src/test/java'
+            PARAM_TEST_PATTERN: '**/*Test*.java'
+          name: Parellel and Selected Tests
+          command: |
+            echo -e "\033[31m\033[4mOrb Notes on Test Splitting\033[0m
+                    \033[34mCaveat 1:\033[0m  CircleCI Test Splitting uses filename by default, but JUnit reports use class names.
+                    Therefore this orb uses naive translation of linux file paths to dot separated package names and strips the .java suffix.
+                    \033[34mCaveat 2:\033[0m  Surefire and Failsafe both allow <includes> in pom configuration (which can come from parent projects).
+                    These values are appended to any -DincludeFiles argument (meaning it would still run all tests on every node).
+                    Therefore this orb will generate an exclusion list; a list of tests being run on the other nodes, and pass that to surefire/failsafe as an exclusion.
+                    \033[34mDebugging:\033[0m This orb will place all files used to decide tests in .circleci/tests and export it as an artifact for inspection/debugging.
+                    "
+            mkdir -p .circleci/tests/
+
+            # generate excluded surefire tests using provided pattern, convert slashes to periods (classnames)
+            circleci tests glob 'src/**/src/test/java/**/*Test*.java' | \
+                sed -e 's#^src/[a-z]*/src/test/java/\(.*\).java#\1#' | \
+                tr "/" "." > .circleci/tests/surefire_classnames
+            cat .circleci/tests/surefire_classnames | circleci tests run --command 'tr " " "," | xargs -I {} ./mvnw -B  -DfailIfNoTests=false -Dtest={} test' --verbose --split-by=timings  
+      - run: 
+          name: aggregate all module tests
+          when: always
+          command: |
+            for SERVICE in "balancereader" "ledgerwriter" "transactionhistory"; do
+            echo "checking $SERVICE..."
+            # save current working dir to memory and cd to src/$SERVICE
+            cp src/$SERVICE/target/surefire-reports/*.xml test-reports || echo "No tests for this node"
+            # return to previously saved path
+            done
       - store_test_results:
           path: test-reports
       - store_artifacts:
           path: test-reports
-
+      - store_artifacts:
+          path: .circleci/tests/
   skaffold-build-push:
       executor: jdk17
       steps:
