converted python jobs & Skaffold

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -1,4 +1,4 @@
-name: "GHA v CCI pipeline comapare"
+name: "GHA v CCI pipeline compare"
 
 on:
   pull_request:
@@ -30,19 +30,22 @@ jobs:
     container: python:3.8
     steps:
       - uses: actions/checkout@v3
+      - name: Use Python Linter
+        uses: actions/setup-python@v4
+        with:
+            python-version: '3.10' 
       - run: pip install pylint
-      - run:
-          name: Lint Python
-          command: pylint --rcfile=./.pylintrc ./src/*/*.py
+      - run: pylint --rcfile=./.pylintrc ./src/*/*.py
 
   python-test:
-    executor: python38
+    runs-on: ubuntu-latest
+    container: python:3.8
     steps:
-      - checkout
+      - uses: actions/checkout@v3
       - run: mkdir test-reports
-      - run:
-          name: Test Python Services
-          command: |
+      - name: Test Python Services
+        uses: actions/setup-python@v4
+      - run: |
             for SERVICE in "contacts" "userservice"; do
               echo "testing $SERVICE..."
               # save current working dir to memory and cd to src/$SERVICE
@@ -56,76 +59,74 @@ jobs:
               # return to previously saved path
               popd
             done
-      - store_test_results:
-          path: test-reports
-      - store_artifacts:
-          path: test-reports
-
-  java-checkstyle:
-    executor: jdk17
-    steps:
-      - checkout
-      - maven/with_cache:  
-          verify_dependencies: false       
-          steps: 
-          - run: ./mvnw checkstyle:check
-
-
-  java-test-and-code-cov:
-    executor: jdk17
-    steps:
-      - checkout
-      - run: mkdir test-reports
-      - restore_cache:
-          keys:
-            - v2-mvn-full-{{ .Branch }}
-            - v2-mvn-full-
-      - run: mvn dependency:go-offline
-      - save_cache:
-          key: v2-mvn-full-{{ .Branch }}
-          paths:
-            - ~/.m2
-      - run: |
-          ./mvnw test
-          for SERVICE in "balancereader" "ledgerwriter" "transactionhistory"; do
-          echo "checking $SERVICE..."
-          # save current working dir to memory and cd to src/$SERVICE
-          pushd src/$SERVICE
-          ../../mvnw jacoco:report
-          echo "Coverage for $SERVICE:"
-          awk -F, \
-          '{ instructions += $4 + $5; covered += $5 } END \
-          { print covered, "/", instructions, " instructions covered"; \
-          print int(100*covered/instructions), "% covered" }' \
-          target/site/jacoco/jacoco.csv
-          cp target/surefire-reports/*.xml ../../test-reports
-          # return to previously saved path
-          popd
-          done
-      - store_test_results:
-          path: test-reports
-      - store_artifacts:
-          path: test-reports
+      - name: Store Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v2
+        if: always()
+        with:
+            files: |
+              test-reports
+      - name: Store Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+           path: test-reports
+  
 
   skaffold-build-push:
-      executor: jdk17
+      runs-on: ubuntu-latest
+      container: jdk:17.0.3
       steps:
-        - checkout
-        - run: |
+        - uses: actions/checkout@v3
+        - uses: actions/setup-java@v3
+          with:
+            distribution: 'temurin'
+            java-version: '17'
+            cache: 'maven'
+        - name: Build with Maven
+          run: mvn -B package --file pom.xml
+        - name: Install Skaffold
+          run: |
             curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
             sudo install skaffold /usr/local/bin/
-        - load-credentials    
-        - setup_remote_docker:
-            docker_layer_caching: true
-        - restore_cache:
-            keys:
-              - v2-mvn-full-{{ .Branch }}
-              - v2-mvn-full-
-        - restore_cache:
-            keys:
-              - v1-skaffold-{{ .Branch }}
-              - v1-skaffold-
-        - run: |
+
+        - name: Install Vault Agent (if not present)
+          run: |
+            vault -h && exit 0 || echo "Installing vault"
+            #only runs if vault command avbove failed
+            cd /tmp
+            wget https://releases.hashicorp.com/vault/1.12.2/vault_1.12.2_linux_amd64.zip
+            unzip vault_1.12.2_linux_amd64.zip
+            sudo mv vault /usr/local/bin        
+            vault -h    
+
+        - name: Load Credentials from Vault
+          run: |
+            ROLE=${BOA_ENV:-"dev"} #fallback to dev when empty
+            echo "Environment (BOA_ENV ): $BOA_ENV"
+            export VAULT_ADDR="https://vault.cera.circleci-labs.com"
+            export VAULT_TOKEN=`vault write -field=token auth/jwt/login role=boa-$ROLE-deploy jwt=$CIRCLE_OIDC_TOKEN`
+            vault read -format=json secret/data/cluster/boa-pipeline-$ROLE > /tmp/cluster-secret.json
+            jq -r '.data.data | to_entries[] | "export K8S_"+(.key | ascii_upcase)+"="+(.value | @sh) ' /tmp/cluster-secret.json >> $BASH_ENV
+            vault read -format=json secret/data/nexus/boa-deployer > /tmp/nexus-secret.json
+            jq -r '.data.data | to_entries[] | "export NEXUS_"+(.key | ascii_upcase)+"="+(.value | @sh) ' /tmp/nexus-secret.json >> $BASH_ENV
+
+
+        - name: Docker Layer Caching     
+          uses: satackey/action-docker-layer-caching@v0.0.11
+          continue-on-error: true
+          run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
+
+        
+        - restore-keys: |
+            - v2-mvn-full-{{ .Branch }}
+            - v2-mvn-full-
+
+        - restore-keys: |
+            - v1-skaffold-${{ hashFiles('**/skaffold.yaml') }}
+            - v1-skaffold-
+            - v1-
+
+        - name: Export Docker Tag to Nexus  
+          run: |
             export DOCKER_TAG=build$(git rev-parse HEAD:src)
             echo "${NEXUS_PASSWORD}" | docker login --username ${NEXUS_USERNAME} --password-stdin docker.nexus.cera.circleci-labs.com
             # seems like skaffold jib needs a eird kick, hit me locally, passes on second run
@@ -133,71 +134,24 @@ jobs:
             mkdir output
             skaffold build --build-concurrency=4 --default-repo=docker.nexus.cera.circleci-labs.com --file-output=output/tags.json
             ls /tmp/
-        - save_cache:
-            key: v1-skaffold-{{ .Branch }}
-            paths:
-              - ~/.skaffold/cache
-        - persist_to_workspace:
-            root: output
-            paths: [ 'tags.json' ]
- 
 
-  deploy:
-    executor: base
-    parameters:
-      boa-environment:
-        type: string
-        default: dev
-        description: Environment suffix used by namesapce and SA account name.
-    environment:
-      BOA_ENV: <<parameters.boa-environment>>
-    steps:
-      - checkout
-      - load-credentials
-      - run: echo "Now using ${K8S_USER}@${K8S_NAMESPACE}"
-      - run: |
-          sudo apt update && sudo apt install kubectl -y
-          echo ${K8S_CERT} | base64 -d > ca.crt
-          kubectl config set-cluster ${K8S_CLUSTER} --server=${K8S_URL} --certificate-authority=ca.crt
-          export DECODED_TOKEN=$(echo ${K8S_TOKEN} | base64 -d) #kubectl prints an encoded value, MUST decode it to work.
-          kubectl config set-credentials ${K8S_USER} --token=${DECODED_TOKEN}
-          kubectl config set-context default --user=${K8S_USER}  --cluster=${K8S_CLUSTER} --namespace ${K8S_NAMESPACE}
-          kubectl config use-context default
-          kubectl get serviceaccounts -n ${K8S_NAMESPACE}
-      - attach_workspace:
-          at: output
-      - run: 
-          name: Deploy BoA
-          command: |
-            curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
-            sudo install skaffold /usr/local/bin/
-            skaffold deploy --default-repo=docker.nexus.cera.circleci-labs.com --namespace=${K8S_NAMESPACE} --build-artifacts=output/tags.json
-      - run:
-          name: Wait for deployment
-          command: |
-            kubectl wait deployment -n ${K8S_NAMESPACE} frontend --for condition=Available=True --timeout=90s
-      - run: 
-          name: Print Frontend URL
-          command: kubectl get service frontend -n ${K8S_NAMESPACE} | awk '{print $4}'
-  e2e:
-    executor: with-chrome
-    steps:
-      - checkout
-      - run: 
-          name: Run Cypress Tests
-          command: |
-            cd ui-tests
-            npx cypress run \
-            --config baseUrl=https://dev.cera.circleci-labs.com \
-            --browser firefox \
-            --reporter junit \
-            --reporter-options "mochaFile=results/my-test-output-[hash].xml"
-      - store_test_results:
-          path: ui-tests/results
-      - store_artifacts:
-          path: ui-tests/cypress/videos
-      - store_artifacts:
-          path: ui-tests/cypress/screenshots    
+        - name: Cache Skaffold
+          uses: actions/cache@v3
+          with:
+           path: |
+             ~/.skaffold/cache
+           key: v1-skaffold-${{ hashFiles('**/skaffold.yaml') }}
+           restore-keys: v1-skaffold-
+        
+    
+        - name: persist_to_workspace
+          uses: {% data reusables.actions.action-upload-artifact %}
+          with:
+            name: homework
+            path: ./tags.json
+
+  
+  
 
 workflows:
   main:
